services:

  chroma-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - db
    env_file:
     - .env
    volumes:
      - ./assets/chroma.sqlite3:/data/chroma.sqlite3:Z

  streamlit-app:
    build:
      context: .
      dockerfile: ./Containerfile.streamlit
    container_name: streamlit-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    driver: bridge
