apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: streamlit-app
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: streamlit-app
    spec:
      serviceAccountName: streamlit-app-secrets
      containers:
        - env:
            - name: CHROMA_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  key: CHROMA_COLLECTION_NAME
                  name: streamlit-secret
            - name: CHROMA_PERSIST_DIRECTORY
              value: "/data"
            - name: CHUNK_SIZE
              valueFrom:
                secretKeyRef:
                  key: CHUNK_SIZE
                  name: streamlit-secret
            - name: EMBEDDING_MODEL
              value: "/app/models/all-MiniLM-L6-v2"
            - name: GRANITE_OLLAMA_LLM
              valueFrom:
                secretKeyRef:
                  key: GRANITE_OLLAMA_LLM
                  name: streamlit-secret
            - name: LLAMA_OLLAMA_LLM
              valueFrom:
                secretKeyRef:
                  key: LLAMA_OLLAMA_LLM
                  name: streamlit-secret
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: TAVILY_API_KEY
                  name: streamlit-secret
            - name: CHROMA_HOST
              value: "http://chroma-db:8000"
          image: quay.io/oawofolurh/llm-agent-finance-streamlit-app:latest
          name: streamlit-app
          ports:
            - containerPort: 8501
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: streamlit-secret
      restartPolicy: Always
